# Homework 4, MA346/MA705, Spring 2026

Due: April 20, 2026

## Purpose of this assignment

Recall the following requirement of Project 2 for our course.

 * Demonstrate that you know how to merge/join data.
    * Your project must include at least two datasets, and you must merge or join them in a logical and useful way.
    * Examples:
       * In sports, merge player performance data in each year with other information from the same year (e.g., player salary, player's team success, etc.)
       * In business, merge an organization's financial data with less quantitative information about the organization (e.g., sector, policies, scandals, new products, etc.)
       * With data about countries, merge health-related measures with economic-related measures

The reason we're doing this assignment is to give you a chance to practice this essential piece of Project 2 and get feedback on it before your final project grade depends upon it.  If you make a mistake on this homework assignment, then even though it will cost your homework grade something, the feedback will improve your Project 2 grade, which is 30% of the course grade.  That's a good deal!

## Steps to complete this assignment

- Work in this notebook\.  Feel free to share it with the partner you've chosen for Project 2\.  You'll be working together on this homework assignment, just as you are working together on the project\.

- Place in the same folder as this notebook the two datasets you plan to use in Project 2\.  The work you do on this homework assignment, if it goes well, will become part of your final project\.  \(If my feedback on this homework assignment reveals to you any problems that require you to switch to different data sets, that’s okay, you're not locking yourself in by importing data sets into this homework assignment\.\)

- Answer all the questions in the section below entitled, "Questions about your data\."  Place your answers directly into this notebook as markdown cells \(not code cells\), just like the questions themselves\.

- Write Python code that loads both data sets into this notebook\.  See the section of the workbook below set aside for this purpose\.  If your data sets need to be cleaned before you merge them, feel free to add code for that as well, but if your data doesn't happen to need cleaning, that's fine\.

- Write Python code that merges both data sets\.  See the section of the workbook below set aside for this purpose\.

- Verify that your merge meets all of your expectations\.  Think about what kinds of checks you could do that make sense for your data\.  Do you need to check the resulting number of rows or columns?  Do you need to use the validate parameter to `pd.merge()`?  Would it be helpful to visualize the merged data in some way?  Not all of these apply to every situation, but this assignment requires you to discern at least one sensible way to check that your merged results are as you expected\.  Report what you find in the section of the workbook below set aside for this purpose\.

- Export your merged data set to a file\.  You can choose what kind of file makes sense for your project\.  For example, we used Parquet in class when there were complex data types \(dates, categorical, etc\.\) that needed to be preserved, and CSV at other times \(when the data was simpler or needed to be shared with non\-technical users\)\.

- Submit your homework on Brightspace\.  Your team will together turn in just one result for this homework assignment, just as you will for Project 2\.  Submit this notebook and the two data sets you merged\.  Or if you chose to do the work inside Deepnote, you can submit just the link to that Deepnote project, as long as you have set the sharing permissions correctly on the project before you submit\.

## Questions about your data

### \(worth 30%, or 6% per question\)

Q1: What are the observational units in the first data set \(the one you will use as the left\-hand one in the merge\)?

A1: The observational units in the first dataset are U.S. states in 2024. Each row represents one state and includes unemployment-related measures for that state.

Q2: What are the observational units in the second data set \(the one you will use as the right\-hand one in the merge\)?

A2: The observational units in the second dataset are also U.S. states in 2024. Each row represents one state and includes violent crime measures for that state.

Q3: What will the observational units be in the merged data set you expect to have as a result of this assignment?

A3: The observational units in the merged dataset will be U.S. states in 2024. After merging the two datasets by state and year, each row will represent one state with both unemployment and violent crime variables in the same row.

Q4: Will you be doing a left, right, inner, or outer join?  Don't just state the answer in one word, but give a reason why your answer makes sense for the two data sets you have \(and possibly also your goals for the merge, if appropriate\)\.

A4: I will use an inner join. An inner join makes sense because I only want rows that appear in both data sets, so that each state in the merged table has both unemployment data and violent crime data for 2024. Since my goal is to analyze the relationship between unemployment and violent crime across states, I need complete information from both sources for the same observational unit. An inner join helps avoid keeping rows with missing values from one of the two data sets.

Q5: How many rows and columns do you expect to have in the merged data set, and what is your reason for each of those numbers?

A5: I expect the merged data set to have 50 rows and 13 columns. I expect 50 rows because both cleaned data sets contain one row for each of the 50 U.S. states for the year 2024, and the state names match across both files. I expect 13 columns because the first data set has 10 columns and the second data set has 5 columns, but the merge will use the shared keys state and year, so those 2 columns should only appear once in the final merged data set. That gives 10 + 5 - 2 = 13 columns.

## Import both data sets

### \(worth 10%, or 5% per data set\)

Write Python code below that loads the two data sets into this notebook and displays both\.

Note: This is one of those times where you should NOT use `print()` or `df.head()`\.

If your data sets need any cleaning or other manipulation done to prepare them for the merge in the next section, you may do that here as well\.  Use as many code cells as your work needs\.

In [2]:
# Place your code here.  Use more than one cell if needed.
import pandas as pd

bls = pd.read_csv("bls_data.csv")
crime = pd.read_csv("CIUS_Crime_in_the_United_States_byState_2024.csv")

bls = bls.rename(columns={
    "FIPS Code": "fips_code",
    "State": "state",
    "Year": "year",
    "Civilian non-institutional population": "civilian_noninstitutional_population",
    "Total": "civilian_labor_force_total",
    "Percent of population": "civilian_labor_force_pct",
    "Total_Employment": "total_employment",
    "Percent of population.1": "employment_pct",
    "Total_Unemployment": "total_unemployment",
    "Rate": "unemployment_rate"
})

bls["state"] = bls["state"].str.strip()
crime["state"] = crime["state"].str.strip()

bls["year"] = pd.to_numeric(bls["year"], errors="coerce")
crime["year"] = pd.to_numeric(crime["year"], errors="coerce")

bls
crime

             state  year  population violent_crime_total  violent_crime_rate
0      Connecticut  2024   3,675,069              4,998                136.0
1            Maine  2024   1,405,012              1,406                100.1
2    Massachusetts  2024   7,136,171             22,457                314.7
3    New Hampshire  2024   1,409,032              1,551                110.1
4     Rhode Island  2024   1,112,308              1,708                153.6
5          Vermont  2024     648,493              1,421                219.1
6       New Jersey  2024   9,500,851             20,684                217.7
7         New York  2024  19,867,248             75,528                380.2
8     Pennsylvania  2024  13,078,751             32,123                245.6
9         Illinois  2024  12,710,158             36,756                289.2
10         Indiana  2024   6,924,275             21,669                312.9
11        Michigan  2024  10,140,459             44,043                434.3
12            Ohio  2024  11,883,304             34,898                293.7
13       Wisconsin  2024   5,960,975             16,602                278.5
14            Iowa  2024   3,241,488              7,885                243.3
15          Kansas  2024   2,970,606             13,033                438.7
16       Minnesota  2024   5,793,151             14,868                256.6
17        Missouri  2024   6,245,466             28,857                462.0
18        Nebraska  2024   2,005,465              4,423                220.5
19    North Dakota  2024     796,568              2,026                254.3
20    South Dakota  2024     924,669              3,350                362.3
21        Delaware  2024   1,051,917              3,795                360.8
22         Florida  2024  23,372,215             62,423                267.1
23         Georgia  2024  11,180,878             36,420                325.7
24        Maryland  2024   6,263,220             26,330                420.4
25  North Carolina  2024  11,046,024             41,511                375.8
26  South Carolina  2024   5,478,831             23,927                436.7
27        Virginia  2024   8,811,195             19,200                217.9
28   West Virginia  2024   1,769,979              4,404                248.8
29         Alabama  2024   5,157,699             18,561                359.9
30        Kentucky  2024   4,588,372              9,779                213.1
31     Mississippi  2024   2,943,045              6,194                210.5
32       Tennessee  2024   7,227,750             42,807                592.3
33        Arkansas  2024   3,088,354             17,893                579.4
34       Louisiana  2024   4,597,740             23,900                519.8
35        Oklahoma  2024   4,095,393             17,316                422.8
36           Texas  2024  31,290,831            121,845                389.4
37         Arizona  2024   7,582,384             31,991                421.9
38        Colorado  2024   5,957,493             28,378                476.3
39           Idaho  2024   2,001,619              4,616                230.6
40         Montana  2024   1,137,233              4,816                423.5
41          Nevada  2024   3,267,467             13,135                402.0
42      New Mexico  2024   2,130,256             15,276                717.1
43            Utah  2024   3,503,613              8,045                229.6
44         Wyoming  2024     587,618              1,195                203.4
45          Alaska  2024     740,133              5,359                724.1
46      California  2024  39,431,263            191,641                486.0
47          Hawaii  2024   1,446,146              3,148                217.7
48          Oregon  2024   4,272,371             14,143                331.0
49      Washington  2024   7,958,180             25,950                326.1

## Merge the two data sets

### \(worth 20%\)

In [3]:
# Place your code here.  Use more than one cell if needed.
merged_df = pd.merge(
    bls,
    crime,
    on=["state", "year"],
    how="inner"
)

merged_df

,fips_code,state,year,civilian_noninstitutional_population,civilian_labor_force_total,civilian_labor_force_pct,total_employment,employment_pct,total_unemployment,unemployment_rate,population,violent_crime_total,violent_crime_rate
0,1,Alabama,2024,"4,096,918","2,359,390",57.6,"2,289,120",55.9,"70,270",3.0,"5,157,699","18,561",359.9
1,2,Alaska,2024,"553,822","360,367",65.1,"344,005",62.1,"16,362",4.5,"740,133","5,359",724.1
2,4,Arizona,2024,"6,041,127","3,741,665",61.9,"3,602,956",59.6,"138,709",3.7,"7,582,384","31,991",421.9
3,5,Arkansas,2024,"2,426,129","1,411,833",58.2,"1,362,381",56.2,"49,452",3.5,"3,088,354","17,893",579.4
4,6,California,2024,"31,646,522","19,692,824",62.2,"18,650,672",58.9,"1,042,152",5.3,"39,431,263","191,641",486.0
5,8,Colorado,2024,"4,815,264","3,265,465",67.8,"3,130,455",65.0,"135,010",4.1,"5,957,493","28,378",476.3
6,9,Connecticut,2024,"3,001,078","1,932,754",64.4,"1,868,860",62.3,"63,894",3.3,"3,675,069","4,998",136.0
7,10,Delaware,2024,"851,021","510,899",60.0,"490,887",57.7,"20,012",3.9,"1,051,917","3,795",360.8
8,12,Florida,2024,"19,014,602","11,114,233",58.5,"10,741,571",56.5,"372,662",3.4,"23,372,215","62,423",267.1
9,13,Georgia,2024,"8,799,428","5,423,268",61.6,"5,237,835",59.5,"185,433",3.4,"11,180,878","36,420",325.7
10,15,Hawaii,2024,"1,133,108","682,524",60.2,"663,668",58.6,"18,856",2.8,"1,446,146","3,148",217.7
11,16,Idaho,2024,"1,561,448","996,542",63.8,"960,892",61.5,"35,650",3.6,"2,001,619","4,616",230.6
12,17,Illinois,2024,"10,211,552","6,638,412",65.0,"6,307,121",61.8,"331,291",5.0,"12,710,158","36,756",289.2
13,18,Indiana,2024,"5,452,601","3,472,118",63.7,"3,332,175",61.1,"139,943",4.0,"6,924,275","21,669",312.9
14,19,Iowa,2024,"2,549,473","1,709,319",67.0,"1,655,382",64.9,"53,937",3.2,"3,241,488","7,885",243.3
15,20,Kansas,2024,"2,300,206","1,548,387",67.3,"1,493,815",64.9,"54,572",3.5,"2,970,606","13,033",438.7
16,21,Kentucky,2024,"3,602,683","2,095,496",58.2,"1,994,539",55.4,"100,957",4.8,"4,588,372","9,779",213.1
17,22,Louisiana,2024,"3,589,178","2,086,957",58.1,"1,997,405",55.7,"89,552",4.3,"4,597,740","23,900",519.8
18,23,Maine,2024,"1,176,513","706,563",60.1,"685,347",58.3,"21,216",3.0,"1,405,012","1,406",100.1
19,24,Maryland,2024,"4,975,111","3,240,844",65.1,"3,137,930",63.1,"102,914",3.2,"6,263,220","26,330",420.4
20,25,Massachusetts,2024,"5,901,781","3,920,504",66.4,"3,764,385",63.8,"156,119",4.0,"7,136,171","22,457",314.7
21,26,Michigan,2024,"8,173,307","5,060,760",61.9,"4,823,521",59.0,"237,239",4.7,"10,140,459","44,043",434.3
22,27,Minnesota,2024,"4,603,986","3,137,560",68.1,"3,039,323",66.0,"98,237",3.1,"5,793,151","14,868",256.6
23,28,Mississippi,2024,"2,312,029","1,274,775",55.1,"1,234,022",53.4,"40,753",3.2,"2,943,045","6,194",210.5
24,29,Missouri,2024,"4,946,070","3,143,051",63.5,"3,026,902",61.2,"116,149",3.7,"6,245,466","28,857",462.0
25,30,Montana,2024,"916,736","577,376",63.0,"560,046",61.1,"17,330",3.0,"1,137,233","4,816",423.5
26,31,Nebraska,2024,"1,553,930","1,078,216",69.4,"1,048,970",67.5,"29,246",2.7,"2,005,465","4,423",220.5
27,32,Nevada,2024,"2,613,852","1,640,898",62.8,"1,552,386",59.4,"88,512",5.4,"3,267,467","13,135",402.0
28,33,New Hampshire,2024,"1,176,653","770,666",65.5,"750,824",63.8,"19,842",2.6,"1,409,032","1,551",110.1
29,34,New Jersey,2024,"7,656,765","4,899,384",64.0,"4,672,089",61.0,"227,295",4.6,"9,500,851","20,684",217.7
30,35,New Mexico,2024,"1,701,256","981,492",57.7,"941,313",55.3,"40,179",4.1,"2,130,256","15,276",717.1
31,36,New York,2024,"16,318,569","9,928,106",60.8,"9,514,544",58.3,"413,562",4.2,"19,867,248","75,528",380.2
32,37,North Carolina,2024,"8,774,760","5,295,197",60.3,"5,101,603",58.1,"193,594",3.7,"11,046,024","41,511",375.8
33,38,North Dakota,2024,"612,694","424,634",69.3,"414,385",67.6,"10,249",2.4,"796,568","2,026",254.3
34,39,Ohio,2024,"9,464,520","5,930,015",62.7,"5,671,397",59.9,"258,618",4.4,"11,883,304","34,898",293.7
35,40,Oklahoma,2024,"3,168,358","1,998,552",63.1,"1,934,503",61.1,"64,049",3.2,"4,095,393","17,316",422.8
36,41,Oregon,2024,"3,502,918","2,192,526",62.6,"2,098,204",59.9,"94,322",4.3,"4,272,371","14,143",331.0
37,42,Pennsylvania,2024,"10,591,537","6,571,898",62.0,"6,321,263",59.7,"250,635",3.8,"13,078,751","32,123",245.6
38,44,Rhode Island,2024,"919,874","593,828",64.6,"568,593",61.8,"25,235",4.2,"1,112,308","1,708",153.6
39,45,South Carolina,2024,"4,387,425","2,562,615",58.4,"2,457,287",56.0,"105,328",4.1,"5,478,831","23,927",436.7
40,46,South Dakota,2024,"713,285","485,148",68.0,"476,298",66.8,"8,850",1.8,"924,669","3,350",362.3
41,47,Tennessee,2024,"5,764,509","3,458,701",60.0,"3,341,996",58.0,"116,705",3.4,"7,227,750","42,807",592.3
42,48,Texas,2024,"24,109,743","15,628,870",64.8,"14,985,161",62.2,"643,709",4.1,"31,290,831","121,845",389.4
43,49,Utah,2024,"2,660,763","1,826,314",68.6,"1,766,489",66.4,"59,825",3.3,"3,503,613","8,045",229.6
44,50,Vermont,2024,"544,322","353,463",64.9,"345,352",63.4,"8,111",2.3,"648,493","1,421",219.1
45,51,Virginia,2024,"6,976,635","4,552,283",65.3,"4,419,514",63.3,"132,769",2.9,"8,811,195","19,200",217.9
46,53,Washington,2024,"6,378,118","4,039,646",63.3,"3,858,057",60.5,"181,589",4.5,"7,958,180","25,950",326.1
47,54,West Virginia,2024,"1,432,747","789,616",55.1,"757,628",52.9,"31,988",4.1,"1,769,979","4,404",248.8
48,55,Wisconsin,2024,"4,813,091","3,142,859",65.3,"3,048,369",63.3,"94,490",3.0,"5,960,975","16,602",278.5
49,56,Wyoming,2024,"465,177","292,189",62.8,"283,060",60.8,"9,129",3.1,"587,618","1,195",203.4

## Verify the merge

### \(worth 30%\)

See the instructions above for ways that can be useful for verifying a merge\.

Add here as many code cells and/or text cells as you need to do the verification and also to explain what you are doing\.  Do not run code without explaining what it means and why it shows that your merge went correctly\.

In [4]:
merged_df.shape

(50, 13)

This shows the size of the merged data set. I expect it to have 50 rows and 13 columns. There should be 50 rows because both cleaned data sets contain one row for each U.S. state in 2024. There should be 13 columns because the first data set has 10 columns and the second has 5 columns, and the shared merge keys state and year only appear once in the merged result.

In [5]:
merged_df.columns

Index(['fips_code', 'state', 'year', 'civilian_noninstitutional_population',
       'civilian_labor_force_total', 'civilian_labor_force_pct',
       'total_employment', 'employment_pct', 'total_unemployment',
       'unemployment_rate', 'population', 'violent_crime_total',
       'violent_crime_rate'],
      dtype='object')

This helps verify that the merged data set includes variables from both original data sets. I should see unemployment-related columns from the BLS data and violent-crime-related columns from the FBI data in the same table.

In [6]:
merged_df[["state", "year", "unemployment_rate", "violent_crime_rate"]]

             state  year  unemployment_rate  violent_crime_rate
0          Alabama  2024                3.0               359.9
1           Alaska  2024                4.5               724.1
2          Arizona  2024                3.7               421.9
3         Arkansas  2024                3.5               579.4
4       California  2024                5.3               486.0
5         Colorado  2024                4.1               476.3
6      Connecticut  2024                3.3               136.0
7         Delaware  2024                3.9               360.8
8          Florida  2024                3.4               267.1
9          Georgia  2024                3.4               325.7
10          Hawaii  2024                2.8               217.7
11           Idaho  2024                3.6               230.6
12        Illinois  2024                5.0               289.2
13         Indiana  2024                4.0               312.9
14            Iowa  2024                3.2               243.3
15          Kansas  2024                3.5               438.7
16        Kentucky  2024                4.8               213.1
17       Louisiana  2024                4.3               519.8
18           Maine  2024                3.0               100.1
19        Maryland  2024                3.2               420.4
20   Massachusetts  2024                4.0               314.7
21        Michigan  2024                4.7               434.3
22       Minnesota  2024                3.1               256.6
23     Mississippi  2024                3.2               210.5
24        Missouri  2024                3.7               462.0
25         Montana  2024                3.0               423.5
26        Nebraska  2024                2.7               220.5
27          Nevada  2024                5.4               402.0
28   New Hampshire  2024                2.6               110.1
29      New Jersey  2024                4.6               217.7
30      New Mexico  2024                4.1               717.1
31        New York  2024                4.2               380.2
32  North Carolina  2024                3.7               375.8
33    North Dakota  2024                2.4               254.3
34            Ohio  2024                4.4               293.7
35        Oklahoma  2024                3.2               422.8
36          Oregon  2024                4.3               331.0
37    Pennsylvania  2024                3.8               245.6
38    Rhode Island  2024                4.2               153.6
39  South Carolina  2024                4.1               436.7
40    South Dakota  2024                1.8               362.3
41       Tennessee  2024                3.4               592.3
42           Texas  2024                4.1               389.4
43            Utah  2024                3.3               229.6
44         Vermont  2024                2.3               219.1
45        Virginia  2024                2.9               217.9
46      Washington  2024                4.5               326.1
47   West Virginia  2024                4.1               248.8
48       Wisconsin  2024                3.0               278.5
49         Wyoming  2024                3.1               203.4

This lets me visually confirm that each row now contains both unemployment data and violent crime data for the same state and year. That is the exact goal of the merge.

## Export your merged data set

### \(worth 10%\)

In [7]:
# Place your code here.  Use more than one cell if needed.
merged_df.to_csv("merged_unemployment_crime_2024.csv", index=False)